-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 16:11:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `Students_id` INT NOT NULL,
  `Students_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `img` JSON NULL,
  PRIMARY KEY (`Students_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `Category_number` INT NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `publish_year` DATE NOT NULL,
  PRIMARY KEY (`Category_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `Book_id` INT NOT NULL,
  `Book_name` VARCHAR(45) NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `publish_year` DATE NOT NULL,
  `Students_Students_id` INT NULL,
  `Category_number` INT NOT NULL,
  PRIMARY KEY (`Book_id`, `Category_number`),
  INDEX `fk_Book_Students1_idx` (`Students_Students_id` ASC) VISIBLE,
  INDEX `fk_Book_Category1_idx` (`Category_number` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Students1`
    FOREIGN KEY (`Students_Students_id`)
    REFERENCES `mydb`.`Students` (`Students_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_Category1`
    FOREIGN KEY (`Category_number`)
    REFERENCES `mydb`.`Category` (`Category_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BorrowOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BorrowOrder` (
  `BorrowOrder_id` INT NOT NULL,
  `date_order` DATE NULL,
  `date_return` DATE NULL,
  `Book_Book_id` INT NOT NULL,
  `Students_id` INT NOT NULL,
  PRIMARY KEY (`BorrowOrder_id`, `Book_Book_id`, `Students_id`),
  INDEX `fk_BorrowOrder_Book_idx` (`Book_Book_id` ASC) VISIBLE,
  INDEX `fk_BorrowOrder_Students1_idx` (`Students_id` ASC) VISIBLE,
  CONSTRAINT `fk_BorrowOrder_Book`
    FOREIGN KEY (`Book_Book_id`)
    REFERENCES `mydb`.`Book` (`Book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BorrowOrder_Students1`
    FOREIGN KEY (`Students_id`)
    REFERENCES `mydb`.`Students` (`Students_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
